Stuff
homegamesio/squish pull request #3
Opened 2020-07-15 01:06 UTC by prosif

Add new squish functionality to support complex shapes, text color and styling, node effects, probably some other stuff too

2020-07-15 01:09 UTC, prosif commented
Need to rebase this on your changes @YazeedLoonat, but I'm putting it up for review because its not going to change much with the rebase

2020-08-01 00:29 UTC, prosif commented
Rebased on master

2020-08-09 19:17 UTC, YazeedLoonat requested changes
Hey I think the rebase caused a few problems
1) with tests, the changes to what npm test does are a rollback of the changes that were in master
2) usage of the Colors.js file seem to be using the older way this file functioned

Examples being importing `Colors` and then trying to use `colors.Black` which doesn't exist anymore and should instead be `Colors.Colors.Black` 

3) this is also failing CI because of those changes. Can you address or I can take a peak in and start to make the updates

2020-08-09 19:17 UTC, YazeedLoonat commented on package.json
> +    "test": "node test.js"
I think the change here is a mistake to what was in master
We should use the testRunner here and the ./test/test.js file should probably be changed to use the testRunner instead

2020-08-19 01:43 UTC, prosif commented
Updated to fix tests as well as a bug with the ShapeUtils array dimension

2020-08-20 02:30 UTC, prosif commented
@YazeedLoonat is this good to merge? I have more changes based on this branch and I don't want to create a chain of PRs

2020-08-28 00:55 UTC, merged